insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("노트북", "computer", 370, "애플", 200, "MacBook Pro")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("TV", "home_applices", 300, "LG", 100, "OLED")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("운동화", "shoes", 10, "아디다스", 500, "초경량 조깅화")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("데스크탑", "computer", 500, "삼성전자", 200, "우수한 성능")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("냉장고", "home_applices", 250, "LG", 150, "LG 디오스 냉장고")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("세탁기", "home_applices", 200, "삼성전자", 100, "AI 맞춤세탁")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("샌들", "shoes", 3, "휠라", 2000, "편해요")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("청소기", "home_applices", 130, "LG", 300, "무선")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("슬리퍼", "shoes", 5, "크록스", 500, "가벼워요")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("에어컨", "home_applices", 300, "삼성전자", 1000, "무풍 에어컨")
